# =========================
# Data configuration
# =========================
Project_name: "Predictive_Maintenance_v1"
author: "Rohit_S_am23s006"

data:
  raw_path: "data/raw/v1_raw.csv"
  no_of_features: 6
  processed_dir: "data/processed/v3_cleaned.csv"
  current_version: "v3"
  cols_to_drop: ["UDI", "Product ID"]
  #train_size: 7000

preprocessing:
  categorical_feature_index: 0
  numeric_feature_indices:
    - 1
    - 2
    - 3
    - 4
    - 5


# =========================
# Model configuration
# =========================
model_params:
  train_size: 7000
  solver: "lbfgs"
  max_iter: 1000
  algorithm: "RandomForest"
  n_estimators: 100
  max_depth: 10
  random_state: 42
  manual_log_path: "models/model_metadata.log"

deployment:
  model_dir: "models"
  metadata_path: models/metadata.json
  port: 5000
  threshold: 0.75
  test_samp: 100
  data_dir: "data/production/v3_day2.csv"

#artifacts:
 # model_dir: artifacts/models
  #metadata_dir: artifacts/metadata
# =========================
# Preprocessing configuration
# =========================
monitoring:
  max_error_rate: 0.20
model:
  version: v2
result :
  Exact match accuracy: 0.9853333333333333
  Target 1 accuracy: 0.9880
  Target 2 accuracy: 0.9950
  Target 3 accuracy: 1.0000
  Target 4 accuracy: 0.9973
  Target 5 accuracy: 0.9967
  Target 6 accuracy: 0.9993
